import type { ForestEncyclopediaCopy, ForestEncyclopediaSlug } from '../data/solutions-forests';

export const en: Record<ForestEncyclopediaSlug, ForestEncyclopediaCopy> = {
  'sustainable-forestry': {
    title: 'Sustainable forestry',
    hook: 'Slow-growing timber still pulls logging into old forests. Managed planted stands and national inventories already supply a large share of industrial wood — they are not a wild forest by another name.',
    imageAlt: 'Misty forestry track with stacked logs and rows of plantation trees',
    what: [
      'Sustainable forest management is the long practice of growing, measuring, and harvesting wood so a forest keeps producing timber and other services. FAO’s overview treats it as management that maintains the forest’s capacity — not a slogan and not a ban on cutting. Slow-growing timber still pulls logging into old forests when markets want boards and pulp. Fast-growing planted species and planned harvest of existing managed forests are the ordinary industrial answer.',
      'FAO’s Global Forest Resources Assessment 2020 puts planted forest at about 294 million hectares — roughly 7 percent of the world’s forest. About 131 million hectares of that are plantations: intensively managed, even-aged, often one or two species, grown mainly for wood. The rest of the planted area was established or restocked but is not run as a short-rotation crop. FAO’s planted-forest pages note that planted forests supplied about 45 percent of industrial roundwood in 2014. Those figures are FAO’s, not a carbon-market claim.',
      'A plantation is not a wild forest. It does not replace primary woodland or mixed old growth. It is a wood factory with rows, roads, and a rotation. Sustainable forestry as FAO describes it includes planted stands and the inventory-and-cut systems used in naturally regenerated production forest. This page is that industrial and national-inventory practice — not shade coffee, community titles, or reduced-impact logging in uncut tropics.',
    ],
    how: [
      'The work is measurement first. National forest inventories count trees, growth, and removals so a harvest plan has a volume, not a hope. Sweden and Finland run among the oldest continuous inventories in Europe: sample plots, increment, and an annual allowable cut that is supposed to stay inside growth. In the United States the Forest Inventory and Analysis program of the USDA Forest Service does the same job on a permanent plot grid — including the South’s planted pine. The inventory does not make a stand sustainable by itself. It makes the overcut visible.',
      'On the ground the method is species choice, stocking, thinning, and a road system that can take the wood out without wrecking the next crop. Planted radiata pine, eucalyptus, and southern pine are grown on rotations measured in decades, not centuries. Fertilizer, weed control, and genetic stock are part of the kit where the owner is running a plantation. In mixed production forest the same idea is a yield table and marked trees. FAO’s planted-forest module is written for that management — establishment, tending, and harvest — not for pretending a row of eucalyptus is a wild reserve.',
    ],
    where: [
      'Northern Europe’s production forests are the textbook inventories: Sweden and Finland grow, measure, and cut on national systems that have run for generations. The stands are managed. They are not untouched taiga. In the United States the South’s pine belt and FIA plots are the named industrial counterpart — planted pine, pulp and sawtimber, and a public inventory.',
      'New Zealand’s radiata pine estate, Chile’s radiata and eucalyptus plantations, and Brazil’s eucalyptus pulp stands are the large Southern Hemisphere planted forests that already feed mills. Smaller planted areas in India, Viet Nam, and Indonesia sit in the same FAO planted-forest class: people put trees on land to grow wood or restore cover. FAO’s 2020 planted-forest and plantation totals are global sums of those national reports. This page does not invent a hectare count for any one country beyond that classification.',
    ],
    limits: [
      'A plantation is not a wild forest. It does not hold the structure, species, or carbon of old primary woodland. Converting a natural forest into rows to “meet demand” is a land-use change, not sustainable forest management. Planted wood can take pressure off some old stands only if the mill buys the planted log and the old forest is left uncut — not if both are cut.',
      'Inventories fail when plots are political, illegal wood is laundered as certified, or the allowable cut is raised to match an oversized mill. Fast-growing species still need water, soil, and a market. They do not restore a biome. Treat sustainable forestry as a way to grow and account for industrial wood — FAO’s 294 million hectares of planted forest, 131 million hectares of plantation, and the 2014 roundwood share — not as a licence to relabel a cleared hillside as a climate project.',
    ],
  },
  'assisted-natural-regeneration': {
    title: 'Assisted natural regeneration',
    hook: 'After cutting and cropping, dry landscapes often stay bare because sprouts are grazed or burned before they can become trees. Assisted natural regeneration protects what is already in the soil — it is not a nursery truck.',
    imageAlt: 'Faidherbia albida trees with feathery green canopy standing in dry golden grass',
    what: [
      'Assisted natural regeneration (ANR) is the deliberate protection and tending of trees that are already trying to return — from roots, stumps, and seed — instead of planting a new stand from a nursery. FAO’s ANR manual treats it as a restoration method: keep fire and livestock off the recruits, release them from weeds and competing sprouts, and let the existing stock become a woodland. After cutting and cropping, dry landscapes often stay bare because those sprouts are grazed or burned before they can become trees. Trucking in seedlings then fails in the same heat.',
      'Farmer-managed natural regeneration (FMNR) is the farm version of the same idea. Chomba and colleagues, writing in Frontiers in Forests and Global Change in 2020, define FMNR as farmers protecting and managing naturally regenerating woody plants on agricultural land — selecting, pruning, and shielding shoots from rootstock or seed. They distinguish it from ANR on forest or abandoned land and from enrichment planting. This page covers that family: protect living stock; do not start from an empty truck.',
      'The photograph is Faidherbia albida, the winter-thorn used in Sahelian parklands. It is the tree most often named in the Niger story, not a generic “shade tree” and not a second agroforestry encyclopedia. FMNR can sit inside agroforestry because trees stand on fields, but the method is regeneration from what is already there — not alley-crop design and not Smithsonian shade-coffee norms.',
    ],
    how: [
      'A farmer or a restoration crew walks a field or a degraded woodland and finds the living stumps and seedlings. They choose which stems to keep, prune competing shoots so one or a few leaders can grow, and protect those stems from goats, cattle, and fire for long enough that they become trees. FAO’s manual describes weeding, firebreaks, and grazing rules as the ordinary tools. There is no requirement for a nursery or a planting day. Enrichment planting can be added later if the seed and root bank is too thin; Chomba and colleagues say that combination should be judged by context, not by a slogan.',
      'Rights matter as much as pruning shears. If the person who protects a sprout does not have a right to the tree, a neighbour or a passing herd will take it. Regreening Africa presents FMNR as one of its restoration approaches: farmer skill, local rules, and time. It is cheap compared with industrial planting in arid country because the plant is already alive. It is not free. Someone must keep the animals off and wait.',
    ],
    where: [
      'The named landscape is south-central Niger — Maradi and Zinder — where Faidherbia parklands returned across millions of hectares after farmers stopped treating every woody shoot as a weed. Chomba and colleagues review that literature and are plain that quantitative evidence for FMNR is still sparse and mainly from those regions. They do not treat every African restoration target as already proven FMNR. This encyclopedia follows that honesty: millions of hectares in Maradi and Zinder are the sourced scale; a global total is not invented here.',
      'Regreening Africa and related programmes have carried FMNR training into other Sahelian and East African landscapes. FAO’s ANR manual is written for forest and woodland restoration more broadly, including places where the remaining root stock is on public or community land rather than a household field. Those are real methods. They are not a proof that every dry hillside will green if a project prints a leaflet.',
    ],
    limits: [
      'ANR and FMNR are not a nursery truck. If the stumps are dead, the seed bank is gone, and the soil is sealed, there is nothing to assist. Chomba and colleagues warn that bold claims outrun the measured evidence outside a few well-studied districts. Combining FMNR with enrichment planting is sometimes necessary; calling every planted seedling “natural regeneration” is not.',
      'Grazing, fire, and insecure tenure undo a season of pruning. A project that pays for training and then leaves without local rights often leaves a bare field. This is not a carbon plantation, not a shade-coffee certification, and not a substitute for stopping clearance of remaining woodland. Treat assisted regeneration as protecting living roots — Niger’s Faidherbia parklands are the named large case — not as a cheap way to claim a forest that is not there.',
    ],
  },
  'fire-smart-forestry': {
    title: 'Prescribed fire',
    hook: 'A century of putting out every fire left dense fuel in many temperate forests. Prescribed burns and thinning restore frequent, low-intensity fire under a written plan — they are not a climate licence to log.',
    imageAlt:
      'Wildland firefighters in protective gear watching a low prescribed burn move through a conifer stand',
    what: [
      'Prescribed fire is the planned ignition of a forest, woodland, or grassland under chosen weather, fuel, and staffing so the fire does a job: consume litter and small fuels, keep shrubs from becoming a ladder, and reopen a stand that used to burn often. The National Wildfire Coordinating Group’s PMS 484 — the Interagency Prescribed Fire Planning and Implementation Procedures Guide, May 2022 — is the U.S. interagency rulebook for that work at the U.S. Forest Service, the Department of the Interior, and partner agencies. It is a planning and implementation standard, not a marketing phrase.',
      'A century of putting out every fire left dense fuel in many temperate forests. When weather is extreme, those stands burn hotter and kill trees that used to survive lighter fire. Fire-smart forestry on this shelf is that maintenance: prescribed fire, often paired with thinning of small trees and ladder fuels, in dry mixed-conifer and similar fire-adapted types. USDA Forest Service General Technical Report 292 reviews how composition and structure in those dry mixed-conifer forests departed from frequent-fire conditions and what treatments are meant to restore. This is not a second sustainable-forestry card about plantations, and it is not a licence to take large live trees because the climate is changing.',
    ],
    how: [
      'PMS 484 requires a written prescribed-fire plan: objectives, prescription windows for weather and fuel moisture, holding resources, contingencies if the fire leaves the unit, smoke, and who is qualified to be burn boss. Ignition starts only when those conditions are met. Crews light in strips or spots so flame length stays in the plan. If the wind shifts or a spot fire goes out the unit, the operation becomes a wildfire and is fought as one. The guide exists because escaped burns are a known failure mode, not a surprise.',
      'Thinning is the other half where stands are too dense for a safe first fire. GTR-292 discusses reducing density and ladder fuels so a low fire can move on the ground instead of into the crowns. The trees taken are the ones that make the next fire severe — small suppressed stems and fuel continuity — not a commercial clearcut dressed as restoration. After the first entries, fire itself does more of the maintenance if managers keep using it. A single burn that is never repeated lets the fuels return.',
    ],
    where: [
      'The named practice is U.S. federal and interagency prescribed fire under PMS 484, used by the Forest Service and Interior bureaus on national forests, rangelands, and wildlife refuges. The card photograph is a Forest Service prescribed burn on the Bitterroot National Forest — a working fire, not a wildfire poster. Dry mixed-conifer restoration in the inland West is the forest type GTR-292 addresses. Indigenous practitioners in the same landscapes have used fire as land care for far longer than the 2022 guide; the encyclopedia does not pretend PMS 484 invented fire.',
      'Similar planned burning is used in parts of Australia and in some European heath and pine systems. Those programmes have their own statutes and weather rules. This page does not invent a global hectare total. It follows the U.S. interagency guide and the dry mixed-conifer technical report that the shelf is built on.',
    ],
    limits: [
      'Prescribed fire does not stop every megafire in a heatwave. When fuels, drought, and wind align, even a treated stand can burn. Poorly planned burns escape. Smoke is a real public-health cost. A burn that is done to “create a carbon project” or to open a road for a timber sale is not the PMS 484 objective.',
      'This is not a climate licence to log. Taking large, fire-resistant trees and calling the skid trail “fuel reduction” is a different activity from thinning plus prescribed fire as GTR-292 describes it. Treat prescribed fire as landscape maintenance under a written prescription — May 2022 PMS 484, U.S. Forest Service and Interior — not as a reason to cut an old stand or as a guarantee against the next extreme season.',
    ],
  },
  'shade-agroforestry': {
    title: 'Shade coffee and cocoa',
    hook: 'Full-sun coffee and cocoa replace forest canopy and cut bird habitat. Smithsonian Bird Friendly shade systems keep a working tree layer over the crop — they are not a second card for agroforestry in general.',
    imageAlt: 'Coffee shrubs growing under a tall shade-tree canopy in a traditional plantation',
    what: [
      'Shade coffee and shade cocoa are crops grown under a tree canopy instead of in an open, full-sun plantation. Full-sun blocks replace forest structure, cut habitat for migratory and resident birds, and often need more fertilizer and irrigation. Traditional and certified shade systems keep coffee or cocoa as the cash crop and keep trees as the roof. This page is that canopy-over-commodity practice. It is not the wider FAO family of alley cropping, silvopasture, and homegardens — that is the Agroforestry card on this shelf.',
      'The Smithsonian Migratory Bird Center’s Bird Friendly certification is the named science standard this encyclopedia follows. Certified farms are organic and deforestation-free. The 25-year account of the programme traces the research to shade-grown farms in Mexico and Guatemala: farms that keep a dense, diverse canopy over coffee can hold bird habitat closer to forest than a sun plantation. The Bird Friendly norms PDF sets the measurable shade and tree-diversity rules used in audits. A traditional shade farm that is not certified can still be this class of agriculture; the Smithsonian pages are the sourced benchmark, not a claim that every shade plot is audited.',
    ],
    how: [
      'Coffee or cocoa stands in the understory. Shade trees — preferably a mix, and under Bird Friendly rules mostly native — form a canopy above. The Smithsonian 25-year article states the agroforestry-pathway thresholds used in certification: an average of 40 percent shade over coffee and 30 percent over cocoa, ten tree species per hectare, and a majority of trees native. A separate forest-conservation pathway sets aside a share of the farm as forest; that is a different compliance route, not a different crop. Organic rules keep insecticides from emptying the insect prey that birds eat.',
      'The farm still has to pick cherries or pods, prune, and sell. Shade does not remove the need for labour or a buyer. Certification is an audit against the norms PDF, not a satellite colour. If the canopy is thinned to a single species of planted Grevillea and the farm is still called “shade,” the bird result is not the Mexico–Guatemala research system. This encyclopedia does not invent a yield penalty or a yield bonus; it describes the structure the Smithsonian programme measures.',
    ],
    where: [
      'The research that launched Bird Friendly was done on shade coffee in Mexico and Guatemala. The photograph on this card is a traditional shade-coffee canopy in Guatemala — the same class of farm, not a named certified estate. The programme later added cocoa and now certifies farms in Latin America and other coffee and cocoa regions under the same bird-habitat idea. Smithsonian’s 25-year page is the sourced history; this article does not invent a country list or a farm count beyond that account.',
      'Uncertified traditional shade systems remain ordinary agriculture in parts of Latin America and West Africa. They are this card’s subject when they keep a real canopy over coffee or cocoa. They are not proof that a sun plantation with a few ornamental trees at the road is “agroforestry,” and they are not the Amazonian Chakra or a Midwestern alley-crop plot — those belong on the Agroforestry page.',
    ],
    limits: [
      'Shade does not automatically stop deforestation if prices push a new clearing at the forest edge. Certification is only as honest as the audit. A Bird Friendly seal is a farm standard, not a national land-use plan. Full-sun intensification still exists because it can raise short-term yield on a given hectare; this page does not invent the size of that gap.',
      'This is not a second agroforestry card. FAO’s three system types — trees with crops, trees with livestock, trees with both — are a wider family. Shade coffee and cocoa are one commodity-under-canopy practice with Smithsonian norms. Do not merge the two slugs. Treat shade coffee and cocoa as a working canopy over a drink crop, researched for 25 years in Mexico and Guatemala — not as a generic tree-planting offset and not as every agroforestry system on Earth.',
    ],
  },
  agroforestry: {
    title: 'Agroforestry',
    hook: 'Clearing trees from cropland and pasture leaves soil, shade, and fodder thinner. FAO treats agroforestry as trees deliberately combined with crops and livestock — a wider family than shade coffee.',
    imageAlt:
      'Aerial view of alley-cropping plots and young tree rows on a Savanna Institute farm beside the Wisconsin River',
    what: [
      'Agroforestry is a collective name for land-use systems in which woody perennials — trees, shrubs, palms, bamboos — are deliberately grown with agricultural crops and/or animals, in space or in time, so the parts interact. FAO’s overview is the definition this page uses. Clearing trees from cropland and pasture leaves soil, shade, and fodder thinner. Farms then lean harder on fertilizer, irrigation, and feed brought from elsewhere. Putting trees back with the farm is the practice; it is not a forest offset and it is not a nursery slogan.',
      'FAO names three main types. Agrisilvicultural systems combine trees and crops — alley cropping, homegardens. Silvopastoral systems combine trees and grazing animals, including on rangeland. Agrosilvopastoral systems combine trees, animals, and crops. Those three types are the map of this card. Shade coffee and cocoa sit in the agrisilvicultural family as a commodity under a canopy, but they have their own encyclopedia page — Smithsonian Bird Friendly norms, Mexico and Guatemala research. This card is the wider FAO family, including systems that have no coffee in them.',
    ],
    how: [
      'Design is local. Species, spacing, and sequence have to fit the climate, the household, and the market. Alley cropping puts rows of trees between strips of annual crop. A homegarden stacks fruit, timber, and vegetables on a small plot. Silvopasture keeps grass and browse under a tree layer so livestock have shade and the trees have a second product. FAO’s FAQs and the SFM-toolbox agroforestry module treat those arrangements as ordinary rural practice that still needs multidisciplinary advice: the wrong tree on a crop field is competition, not a service.',
      'Tenure and time are part of the method. A tree that will be browsed or cut by someone else will not be tended. A seedling row that is never pruned or protected is not a system. FAO stresses that agroforestry should be tailored to the farmer and the place. This encyclopedia does not invent a global yield or a carbon coefficient. It describes the three system types and the named example below.',
    ],
    where: [
      'FAO says agroforestry is a significant feature of agriculture in all regions, more prevalent in Southeast Asia, Central America, and South America, and estimates that about 78 percent of the global area under agroforestry is in the tropics and about 22 percent in temperate regions. Those are FAO’s overview figures, not a Fix Planet census. Temperate alley cropping — the Wisconsin River farm in the card photograph is that class of plot — is the same family in a different climate.',
      'The named traditional system on FAO’s own article is the Amazonian Chakra of Napo Province, Ecuador: a multi-storey agroforestry system managed by Indigenous communities, recognised in FAO’s GIAHS work. Use that FAO article, not a dead third-party GIAHS path. The Chakra is not a shade-coffee estate and not a Great Plains windbreak. It is trees, crops, and community management in Amazonian Ecuador — one documented instance of the wider family.',
    ],
    limits: [
      'A row of seedlings is not a forest offset. Agroforestry does not restore a primary forest, and it does not stop a frontier if the next hectare is still cheaper to clear than to tend. Trees compete with crops for light and water when the design is wrong. Livestock that are not herded will eat the future canopy.',
      'Do not merge this card with shade coffee and cocoa. Those systems are one agrisilvicultural practice with a Smithsonian bird standard; this card is FAO’s three types plus the Napo Chakra. Do not paste Mexico or Tanzania community-forestry numbers here. Treat agroforestry as trees with farms — alley, pasture, homegarden, Chakra — not as a second Bird Friendly page and not as a planted-forest inventory.',
    ],
  },
  windbreaks: {
    title: 'Windbreaks / shelterbelts',
    hook: 'Open fields take the full force of wind: soil blows, snow drifts, livestock burn feed. USDA’s National Agroforestry Center treats windbreaks as designed linear plantings — farm infrastructure, not a carbon plantation.',
    imageAlt: 'Two young rows of staked trees forming a windbreak across a green Illinois field',
    what: [
      'Windbreaks — also called shelterbelts — are linear plantings of trees and shrubs laid out to slow the wind and to do related farm jobs: field protection, livestock shelter, living snow fences, farmstead screening. The USDA National Agroforestry Center’s windbreaks page is the definition this encyclopedia uses. Open fields and yards take the full force of wind. Soil blows, snow drifts onto roads, and animals burn more feed in cold weather. A designed belt of trees is the ordinary Midwestern and Great Plains answer.',
      'NAC is plain that windbreaks are not one size. Location, orientation to the wind, height, width, density, and species decide what the belt does. Some belts are meant mainly to cut wind speed across a crop. Others are meant to hold snow on the field, keep it off a road, shade livestock, or hide a lot. Agroforestry Notes 25 and 36 are the Center’s technical notes on those design choices. This is farm infrastructure. It is not a plantation inventory and not a shade-coffee canopy.',
    ],
    how: [
      'Height sets the protected zone: the quiet air on the leeward side scales with how tall the trees are. Density — how porous the belt is — sets whether the wind drops sharply and then recovers, or is eased over a longer fetch. Gaps become jets; a missing tree is a hole that can scour soil. Orientation is usually across the prevailing damaging wind. Notes 25 and 36 walk through those relationships and through multi-row versus single-row belts, including why a three-row young belt — the Illinois photograph on this card — is a different tool from a mature multi-story shelterbelt.',
      'Establishment is planting, weed control, and replacement of dead trees until the belt closes. Renovation is the later job: old Plains belts have gaps, volunteer trees, and lost density. NAC and its partners work on inventory, establishment, and renovation, including Great Plains windbreak mapping. Specialty shrubs can be added for a second product if harvest does not wreck the wind function. A belt that is never replanted after dieback is a row of snags, not a windbreak.',
    ],
    where: [
      'The named practice is U.S. farm windbreaks as USDA NAC describes them: field belts, livestock belts, living snow fences, and farmstead belts, with a long Great Plains and Midwest history. The card photograph is a young three-row belt in an Illinois field — that class of planting, not a named USDA project. NAC notes that producers use windbreaks mainly for soil, livestock, wind, and snow control, and that satisfaction in the studies it synthesises has been high. This page does not invent a national kilometre total.',
      'Linear shelterbelts also exist in other windy farming regions. This encyclopedia does not copy those programmes onto the USDA notes. The verification links are the NAC windbreaks page and Notes 25 and 36. If a follow-up pack names another country’s belt system with a live source, it can be added; until then the sourced practice is U.S. NAC design.',
    ],
    limits: [
      'Windbreaks fail if they are not maintained. Gaps, neglected rows, and a belt planted parallel to the damaging wind do not protect the field. They are not a carbon plantation: a thin line of trees does not replace a forest inventory or a climate offset. They do not stop a drought. They do not replace a riparian buffer’s job of shading a stream — that is a different card.',
      'A windbreak is not agroforestry in the FAO three-type sense except as one linear silvoarable or farmstead tool, and it is not shade coffee. Treat it as designed farm infrastructure — height, density, orientation, Notes 25 and 36 — not as a woodland restoration and not as a place to invent a yield percentage this page does not have from those notes.',
    ],
  },
  'reduced-impact-logging': {
    title: 'Reduced-impact logging',
    hook: 'Conventional tropical harvest often wrecks the residual stand with unplanned skid trails and hung trees. Reduced-impact logging is planned felling and extraction — not a ban on logging and not the same as leaving an old forest uncut.',
    imageAlt: 'A yellow loader carrying a log at a timber camp in Tawau District, Sabah, with forest behind',
    what: [
      'Reduced-impact logging (RIL) is timber harvesting planned and carried out so damage to the remaining forest is kept down: map the crop trees, lay out roads and skid trails, fell in a chosen direction, and keep machines on the planned trails. Dennis Dykstra’s FAO paper on concepts and issues treats RIL as the application of known harvesting engineering — inventory, supervision, directional felling, vine cutting where crowns are tied — transferred into tropical forests where only a few commercial trees stand on a hectare. Conventional tropical harvest often means poorly planned skid trails, trees hung in climbers, and damage to the next crop. The residual stand and the soil pay first.',
      'W. B. J. Jonkers’s FAO paper traces the first true RIL system for tropical rainforest to late-1970s Sarawak, then to later work in Suriname, Guyana, and Cameroon. Pinard and others used the name “reduced-impact logging” in 1995; Dykstra notes that the term stuck because it was more acceptable than older FAO phrasing. RIL is not sustainable forest management by itself, and it is not a community title. It is a harvesting method. The camp photograph on this card is a logging landing in Sabah — the industry setting, not a named RIL trial plot.',
    ],
    how: [
      'Dykstra’s checklist is the usual sequence. Pre-harvest inventory and mapping of crop trees. Planning of roads, skid trails, and landings to reach those trees while protecting streams. Vine cutting around trees that would otherwise pull neighbours down. Directional felling and careful bucking. Machines stay on marked trails; logs are winched rather than hunted by a skidder wandering the stand. Post-harvest assessment tells the crew what they damaged. Almost all of that is ordinary in temperate industrial forest; the tropical additions are mapping scattered crop trees and cutting vines.',
      'Jonkers shows why the same ideas look different on the ground. Sarawak’s late-1970s method used terrain and tree maps, herring-bone felling toward pre-opened main trails, and the same machines as conventional logging — costs per cubic metre fell and trees destroyed were almost halved even though damage reduction was not the original terms of reference. Guyana and Cameroon adapted trail spacing, vine cutting, and felling aims to poorer stands, clumped species, and, in Cameroon, people living in the forest. The method is planning and supervision, not a new saw.',
    ],
    where: [
      'The named FAO cases are Sarawak (first full system, late 1970s), then Suriname, Guyana (including the Tropenbos work near Mabura Hill), and Cameroon (Tropenbos southwest). Other 1990s studies Jonkers lists — Indonesia, Sabah, Brazil — sit in the same research wave. Dykstra’s paper is the concepts piece: codes of practice, training, and why tropical operations disturb more ground per cubic metre than a Pacific Northwest clearcut of hundreds of cubic metres on a hectare.',
      'Research in those papers found lower damage and, in several trials, costs that were no higher or were lower than conventional logging because less wood was wasted and skidding was shorter. Jonkers and Dykstra are also plain that many firms still do not change practice. This page does not invent a global share of tropical harvest that is RIL. The sourced fact is that the method exists, was tested in those countries, and is not automatically adopted.',
    ],
    limits: [
      'RIL is not a ban on logging and it is not the same as leaving an old forest uncut. A planned harvest still removes trees, opens canopy, and builds roads that can invite settlement — Dykstra notes the extra kilometres of tropical road per cubic metre. If the inventory is a fiction or the skidder leaves the trail, the label is paint.',
      'Training and daily supervision are the constraint both papers name. Without skilled fallers and a supervisor on the ground, RIL is a PDF. It does not create a planted-forest inventory, a community user group, or a bird-friendly coffee farm. Treat it as planned tropical harvesting — Jonkers’s Sarawak, Guyana, and Cameroon cases; Dykstra’s concepts — not as a certificate that the concession is a wilderness.',
    ],
  },
  'riparian-forest-restoration': {
    title: 'Riparian forest restoration',
    hook: 'When streamside trees are cleared, banks erode, nutrients wash in, and summer water warms. USDA Climate Hubs and the Forest Service riparian handbook treat the fix as cover on the bank — local stream work, not a watershed slogan.',
    imageAlt: 'Aerial view of a wooded riparian buffer along a winding creek through farmland in Story County, Iowa',
    what: [
      'Riparian forest restoration is the work of putting woody and other vegetative cover back on the land beside a stream, river, or wet drainage so the bank holds, the water is shaded, and the channel has roots and wood. USDA Climate Hubs describe forests in riparian areas as reducing erosion, buffering high flows, moderating temperature, cutting evaporation, and providing corridors. When those trees are cleared for fields or lots, banks erode, nutrients wash in, and summer water warms. Fish and the channel lose the shade and roots that held the edge.',
      'The companion Climate Hubs page on maintaining or restoring riparian areas and the USDA Forest Service riparian restoration handbook (the low-resolution PDF cited here) are the practice manuals this encyclopedia follows. The aim is shade, woody debris, and soil held by roots — mixed plantings, no-harvest or limited-harvest buffers, and bank stabilization where the toe is failing. This is not a planted-forest inventory, not a windbreak across a dry field, and not community forestry in Nepal. It is the strip of woods along the water.',
    ],
    how: [
      'The Climate Hubs tactics are concrete. Restore a mix of tree and plant species to increase shade, supply wood to the channel, stabilize soil, and reconnect habitat. Reforest riparian ground next to agriculture or development to cut erosion and nutrient loading. Create buffers with reduced or no harvest, sized to landform and hydrology, not only to a single advertised width. Keep canopy and ground cover so rain does not hammer bare soil. Where banks are already failing, anchor with fabric, wire, or natural materials. Where dams or gates exist, manage water so the riparian soil is not left dry at the wrong time.',
      'The Forest Service handbook walks through site assessment, species, planting, and the difference between a living buffer and a rock dump. Planting a single row of one species on a raw bank is not the handbook. Livestock that stand in the channel will undo a season of work. The buffer has to be wide enough for the landform; a decorative line of trees on a straightened ditch is not a restored riparian forest.',
    ],
    where: [
      'The named guidance is U.S. federal: Climate Hubs adaptation approaches for forested watersheds, and the Forest Service riparian restoration handbook. The card photograph is a wooded buffer on Bear Creek in Story County, Iowa — farm country with a tree strip on the creek, the ordinary Midwestern picture of this practice. Similar buffers are used on agricultural streams in other temperate countries; this page does not invent their lengths or a global kilometre total.',
      'Projects run on public forests, on farm conservation contracts, and on urban creeks. They already run. They are not a pilot waiting for a new invention. The sources above are the verification links; they do not claim that every U.S. stream has a buffer.',
    ],
    limits: [
      'A planted strip does not restore a whole watershed if the uplands stay bare. Nutrients and sediment still arrive from the field. A buffer is not a wastewater plant and not a levee. In a large flood the channel will move. In a dry year the plantings die if they were the wrong species for the water table.',
      'This is local stream work. It is not a climate licence to ignore the rest of the catchment, and it is not agroforestry or shade coffee because a few willows were planted. Treat riparian restoration as cover on the bank — Climate Hubs tactics plus the Forest Service handbook — not as a forest-area statistic and not as a substitute for keeping livestock and ploughs out of the water.',
    ],
  },
  'community-forestry': {
    title: 'Community forestry',
    hook: 'When use rights sit only with a distant office, nearby households have little reason to guard a forest they cannot legally use. Nepal’s Forest Act 1993 and the CFUG system are the sourced model on this card — not a copy of Mexico or Tanzania.',
    imageAlt: 'Tall pines and broadleaf trees on a grassy slope in Badikhel community forest, Lalitpur, Nepal',
    what: [
      'Community forestry is forest management in which local people hold recognised rights to use and care for a defined woodland, under rules they help set, instead of the state being the only legal manager. FAO’s older community-forestry note treats that shift of rights and responsibilities as the core idea. When use rights sit only with a distant office, nearby households have little reason to guard a forest they cannot legally use. Illegal cutting and weak upkeep follow. A user-group title is the opposite arrangement: the people next to the trees can harvest what the rules allow and are expected to protect the rest.',
      'This card is Nepal’s system, not a collage of other countries. The Forest Act, 2049 (1993) — the FAOLEX text cited here — is the statute that gave Community Forest User Groups a legal path to manage national forest handed over as community forest. FAO and the Federation of Community Forestry Users Nepal (FECOFUN), in a 28 July 2025 note, describe the present scale: more than 23,000 CFUGs managing about 2.4 million hectares, involving about 16 million people. Those are FAO/FECOFUN’s figures. This page does not add Mexico’s ejidos or Tanzania’s village forests as if they were the same law.',
    ],
    how: [
      'A CFUG is a local assembly with a constitution, an operational plan, and a boundary. The group decides who may take firewood, timber, and forage, what is paid into the group fund, and how patrols run. The 1993 Act is the legal hook that makes that plan more than a village custom. District forest officers remain in the picture; handover is a statutory process, not a slogan. FECOFUN is the users’ federation that bargains with the state and with FAO programmes on training, enterprises, and climate-resilience projects.',
      'The method fails when the group is captured, when women and Indigenous users are left off the committee, or when a market for timber strips the stand faster than the operational plan assumed. FAO and FECOFUN’s 2025 meeting text stresses enterprises, women’s leadership, and transparent data — because a title on paper is not automatic conservation. The photograph is Badikhel community forest in Lalitpur: a named Nepali community forest, not a generic “village woods.”',
    ],
    where: [
      'Nepal is the sourced geography. The 1993 Act applies there. The 2025 FAO/FECOFUN figures — more than 23,000 groups, about 2.4 million hectares, about 16 million people — are Nepal’s community-forestry numbers. Mid-hills districts are the classic landscape; the Churia and eastern programmes mentioned in that FAO note are later layers, not a second country.',
      'Other states run community or village forest schemes under other laws. This encyclopedia does not paste their statistics onto Nepal’s Act. If a later pack adds another country with a live legal text and a live agency figure, it can have its own paragraph. Until then, do not treat this card as Mexico or Tanzania.',
    ],
    limits: [
      'A user-group title is not automatic conservation. Groups can overcut, exclude women, or become a local elite’s woodlot. Markets that pay for clear stems will pressure the operational plan. The state can still reclaim or stall handover. FAO’s 2025 note is a partnership story, not a census of every hectare’s condition.',
      'Do not copy other countries’ community-forestry numbers onto this page. Do not merge this card with sustainable plantations, ANR in Niger, or shade coffee. Treat community forestry here as Nepal’s 1993 Act and the FAO/FECOFUN 2025 scale — more than 23,000 CFUGs, about 2.4 million hectares, about 16 million people — and as a governance method that still needs accountable groups.',
    ],
  },
};
