import type { ForestEncyclopediaCopy, ForestEncyclopediaSlug } from '../data/solutions-forests';

export const pl: Record<ForestEncyclopediaSlug, ForestEncyclopediaCopy> = {
  'sustainable-forestry': {
    title: 'Zrównoważone leśnictwo',
    hook: 'Wolno rosnące drewno wciąż ciągnie wyrąb do starych lasów. Zagospodarowane uprawy i krajowe inwentaryzacje już dają dużą część drewna przemysłowego — to nie dziki las pod inną nazwą.',
    imageAlt: 'Mglista droga leśna ze stosami kłód i rzędami drzew plantacyjnych',
    what: [
      'Zrównoważona gospodarka leśna to dawna praktyka hodowania, mierzenia i pozyskiwania drewna tak, by las nadal dawał surowiec i inne usługi. Przegląd FAO traktuje to jako zarządzanie, które utrzymuje zdolność lasu — nie hasło i nie zakaz wycinki. Wolno rosnące drewno wciąż ciągnie wyrąb do starych lasów, gdy rynek chce desek i masy. Szybko rosnące gatunki sadzone i planowany wyrąb już zagospodarowanych lasów to zwykła odpowiedź przemysłowa.',
      'Global Forest Resources Assessment FAO 2020 stawia las sadzony na około 294 miliony hektarów — mniej więcej 7 procent lasu świata. Około 131 milionów hektarów z tego to plantacje: intensywnie prowadzone, jednowiekowe, często jeden albo dwa gatunki, hodowane głównie na drewno. Reszta powierzchni sadzonej została założona albo uzupełniona, ale nie jest prowadzona jako uprawa o krótkiej rotacji. Strony FAO o lasach sadzonych notują, że lasy sadzone dały około 45 procent przemysłowego drewna okrągłego w 2014 r. To liczby FAO, nie roszczenie rynku węglowego.',
      'Plantacja to nie dziki las. Nie zastępuje lasu pierwotnego ani mieszanego starodrzewu. To fabryka drewna z rzędami, drogami i rotacją. Zrównoważone leśnictwo, jak opisuje je FAO, obejmuje uprawy sadzone oraz systemy inwentaryzacji i wyrębu w lesie produkcyjnym odnawianym naturalnie. Ta strona jest o tej praktyce przemysłowej i krajowej inwentaryzacji — nie o kawie cieniowanej, tytułach wspólnotowych ani o pozyskaniu o zmniejszonym wpływie w nietkniętym tropiku.',
    ],
    how: [
      'Najpierw pomiar. Krajowe inwentaryzacje lasu liczą drzewa, przyrost i pozyskanie, żeby plan wyrębu miał objętość, nie nadzieję. Szwecja i Finlandia prowadzą jedne z najstarszych ciągłych inwentaryzacji w Europie: powierzchnie próbne, przyrost i etat, który ma zostawać wewnątrz przyrostu. W Stanach Zjednoczonych program Forest Inventory and Analysis Służby Leśnej USDA robi to samo na stałej siatce — w tym sadzoną sosnę Południa. Inwentaryzacja sama z siebie nie czyni drzewostanu zrównoważonym. Czyni przerąb widocznym.',
      'W terenie metoda to dobór gatunku, zagęszczenie, trzebieże i sieć dróg, która wywiezie drewno bez niszczenia następnego plonu. Sadzona sosna radiata, eukaliptus i sosna południowa rosną w rotacjach liczonych w dekadach, nie stuleciach. Nawóz, odchwaszczanie i materiał genetyczny są częścią zestawu tam, gdzie właściciel prowadzi plantację. W mieszanym lesie produkcyjnym ta sama idea to tablica zasobności i drzewa oznaczone. Moduł FAO o lasach sadzonych jest napisany dla tego zagospodarowania — założenie, pielęgnacja, wyrąb — nie po to, by udawać, że rząd eukaliptusa jest dzikim rezerwatem.',
    ],
    where: [
      'Lasy produkcyjne Europy Północnej to podręcznikowe inwentaryzacje: Szwecja i Finlandia hodują, mierzą i wycinają w systemach krajowych, które działają od pokoleń. Drzewostany są zagospodarowane. To nie nietknięta tajga. W Stanach Zjednoczonych pas sosny Południa i powierzchnie FIA to nazwany przemysłowy odpowiednik — sadzona sosna, masa i tartak, publiczna inwentaryzacja.',
      'Majątek sosny radiata w Nowej Zelandii, plantacje radiaty i eukaliptusa w Chile oraz eukaliptusowe drzewostany celulozowe Brazylii to wielkie lasy sadzone półkuli południowej, które już karmią zakłady. Mniejsze nasadzenia w Indiach, Wietnamie i Indonezji siedzą w tej samej klasie lasu sadzonego FAO: ludzie sadzą drzewa, by hodować drewno albo wrócić pokrywę. Sumy FAO 2020 dla lasu sadzonego i plantacji to globalne sumy tych sprawozdań krajowych. Ta strona nie wymyśla hektarów dla jednego kraju poza tą klasyfikacją.',
    ],
    limits: [
      'Plantacja to nie dziki las. Nie ma struktury, składu ani węgla starego lasu pierwotnego. Zamiana lasu naturalnego w rzędy, by „zaspokoić popyt”, to zmiana użytkowania ziemi, nie zrównoważona gospodarka. Sadzone drewno zdejmuje presję ze starych drzewostanów tylko wtedy, gdy tartak kupuje sadzoną kłodę, a stary las zostaje — nie gdy tnie się oba.',
      'Inwentaryzacje zawodzą, gdy powierzchnie są polityczne, nielegalne drewno piorą jako certyfikowane albo etat podnoszą pod zbyt duży zakład. Szybko rosnące gatunki wciąż potrzebują wody, gleby i rynku. Nie odtwarzają biomu. Traktujcie zrównoważone leśnictwo jako sposób hodować i rozliczać drewno przemysłowe — 294 miliony hektarów lasu sadzonego FAO, 131 milionów hektarów plantacji i udział drewna okrągłego z 2014 r. — nie jako licencję przemianować wycięty stok w projekt klimatyczny.',
    ],
  },
  'assisted-natural-regeneration': {
    title: 'Wspomagane odnawianie naturalne',
    hook: 'Po wycince i uprawie suche krajobrazy często zostają gołe, bo odrośla są spasane albo palone, zanim staną się drzewami. Wspomagane odnawianie naturalne chroni to, co już jest w glebie — to nie ciężarówka z szkółki.',
    imageAlt: 'Drzewa Faidherbia albida z pierzastą zieloną koroną wśród suchej złotej trawy',
    what: [
      'Wspomagane odnawianie naturalne (ANR) to celowa ochrona i pielęgnacja drzew, które już próbują wrócić — z korzeni, pniaków i nasion — zamiast sadzenia nowego drzewostanu ze szkółki. Podręcznik FAO o ANR traktuje to jako metodę odtwarzania: trzymać ogień i bydło z dala od nalotu, uwalniać go od chwastów i konkurencyjnych pędów i pozwolić istniejącemu zasobowi stać się lasem. Po wycince i uprawie suche krajobrazy często zostają gołe, bo te odrośla są spasane albo palone. Przywiezione sadzonki potem padają w tym samym upale.',
      'Odnawianie naturalne zarządzane przez rolnika (FMNR) to polowa wersja tego samego pomysłu. Chomba i współpracownicy w Frontiers in Forests and Global Change w 2020 r. definiują FMNR jako ochronę i zarządzanie naturalnie odnawiającymi się roślinami drzewiastymi na ziemi rolnej — wybór, przycinanie i osłonę pędów z karpy albo nasienia. Odróżniają to od ANR na ziemi leśnej albo porzuconej i od dolesiania. Ta strona obejmuje tę rodzinę: chronić żywy zasób; nie zaczynać od pustej ciężarówki.',
      'Na zdjęciu jest Faidherbia albida, zimowa akacja parków Sahelu. To drzewo najczęściej nazywane w historii Nigru, nie ogólne „drzewo cienia” i nie druga encyklopedia agroleśnictwa. FMNR może siedzieć wewnątrz agroleśnictwa, bo drzewa stoją na polach, ale metoda to odnawianie z tego, co już jest — nie projekt alei i nie normy Smithsonian dla kawy cieniowanej.',
    ],
    how: [
      'Rolnik albo ekipa odtwarzania chodzi po polu albo zdegradowanym lesie i znajduje żywe pniaki i siewki. Wybierają, które pędy zostawić, przycinają konkurencję, by jeden albo kilka przewodników mogło rosnąć, i chronią te pędy przed kozami, bydłem i ogniem wystarczająco długo, by stały się drzewami. Podręcznik FAO opisuje odchwaszczanie, pasy przeciwogniowe i reguły wypasu jako zwykłe narzędzia. Nie ma wymogu szkółki ani dnia sadzenia. Dolesianie można dodać później, jeśli bank nasion i korzeni jest zbyt cienki; Chomba i współpracownicy piszą, że tę kombinację trzeba oceniać według miejsca, nie hasła.',
      'Prawa znaczą tyle samo co sekator. Jeśli ten, kto chroni pęd, nie ma prawa do drzewa, sąsiad albo przechodzące stado je zabierze. Regreening Africa przedstawia FMNR jako jedno ze swoich podejść do odtwarzania: umiejętność rolnika, lokalne reguły i czas. W kraju suchym jest to tańsze niż sadzenie przemysłowe, bo roślina już żyje. To nie jest darmowe. Ktoś musi trzymać zwierzęta z dala i czekać.',
    ],
    where: [
      'Nazwany krajobraz to południowo-środkowy Niger — Maradi i Zinder — gdzie parki Faidherbia wróciły na miliony hektarów, gdy rolnicy przestali traktować każdy pęd drzewny jako chwast. Chomba i współpracownicy przeglądają tę literaturę i mówią wprost, że ilościowe dowody na FMNR są wciąż rzadkie i głównie z tych regionów. Nie traktują każdego afrykańskiego celu odtwarzania jako już udowodnionego FMNR. Ta encyklopedia idzie za tą uczciwością: miliony hektarów w Maradi i Zinder to sourced skala; globalnej sumy tu nie wymyślamy.',
      'Regreening Africa i pokrewne programy niosły szkolenie FMNR do innych krajobrazów Sahelu i Afryki Wschodniej. Podręcznik FAO o ANR jest napisany dla odtwarzania lasu i zadrzewień szerzej, w tym miejsc, gdzie pozostały zasób korzeni jest na ziemi publicznej albo wspólnotowej, nie na polu gospodarstwa. To realne metody. To nie dowód, że każdy suchy stok zazieleni się, jeśli projekt wydrukuje ulotkę.',
    ],
    limits: [
      'ANR i FMNR to nie ciężarówka ze szkółki. Jeśli pniaki są martwe, bank nasion zniknął, a gleba jest zasklepiona, nie ma czego wspomagać. Chomba i współpracownicy ostrzegają, że śmiałe twierdzenia wyprzedzają zmierzone dowody poza kilkoma dobrze zbadanymi okręgami. Łączenie FMNR z dolesianiem bywa potrzebne; nazywanie każdej sadzonki „odnawianiem naturalnym” nie.',
      'Wypas, ogień i niepewne prawo własności przekreślają sezon przycinania. Projekt, który płaci za szkolenie i odchodzi bez lokalnych praw, często zostawia gołe pole. To nie plantacja węglowa, nie certyfikacja kawy cieniowanej i nie zamiana za zatrzymanie wycinki pozostałego lasu. Traktujcie wspomagane odnawianie jako ochronę żywych korzeni — parki Faidherbia w Nigrze to nazwany duży przypadek — nie jako tani sposób zgłosić las, którego nie ma.',
    ],
  },
  'fire-smart-forestry': {
    title: 'Ogień przepisany',
    hook: 'Wiek gaszenia każdego ognia zostawił gęste paliwo w wielu lasach umiarkowanych. Przepisane wypalenia i trzebieże wracają częsty, niski ogień według pisemnego planu — to nie licencja klimatyczna na wyrąb.',
    imageAlt:
      'Strażacy leśni w ubraniach ochronnych patrzą, jak niski ogień przepisany idzie przez drzewostan iglasty',
    what: [
      'Ogień przepisany to planowe zapalenie lasu, zadrzewienia albo łąki przy wybranej pogodzie, paliwie i obsadzie, żeby ogień zrobił robotę: zjadł ściółkę i drobne paliwo, nie dał krzewom stać się drabiną i znów otworzył drzewostan, który kiedyś palił się często. PMS 484 National Wildfire Coordinating Group — Interagency Prescribed Fire Planning and Implementation Procedures Guide, maj 2022 — to międzyagencyjny statut USA dla tej pracy w Służbie Leśnej, Departamencie Zasobów Wewnętrznych i u partnerów. To standard planowania i wykonania, nie hasło marketingowe.',
      'Wiek gaszenia każdego ognia zostawił gęste paliwo w wielu lasach umiarkowanych. Gdy pogoda jest skrajna, te drzewostany palą się goręcej i zabijają drzewa, które przeżywały lżejszy ogień. Leśnictwo „mądre wobec ognia” na tej półce to ta konserwacja: ogień przepisany, często w parze z trzebieżą drobnych drzew i paliwa drabiny, w suchych mieszanych iglastych i podobnych typach przystosowanych do ognia. General Technical Report 292 Służby Leśnej USDA recenzuje, jak skład i struktura tych suchych mieszanych iglastych odeszły od warunków częstego ognia i jakie zabiegi mają to wrócić. To nie druga karta zrównoważonego leśnictwa o plantacjach i nie licencja brać duże żywe drzewa, bo klimat się zmienia.',
    ],
    how: [
      'PMS 484 wymaga pisemnego planu ognia: cele, okna pogody i wilgotności paliwa, siły utrzymania, postępowanie jeśli ogień wyjdzie z jednostki, dym i kto jest uprawniony być szefem wypalenia. Zapłon zaczyna się tylko gdy te warunki są spełnione. Brygady palą pasami albo punktami, żeby długość płomienia została w planie. Jeśli wiatr się zmieni albo ogień punktowy wyjdzie poza jednostkę, operacja staje się pożarem i gasi się ją jako pożar. Przewodnik istnieje, bo ucieczki wypaleń to znany tryb awarii, nie niespodzianka.',
      'Trzebież to druga połowa tam, gdzie drzewostan jest zbyt gęsty na bezpieczny pierwszy ogień. GTR-292 omawia zmniejszanie zagęszczenia i paliwa drabiny, żeby niski ogień szedł po ziemi, nie w korony. Bierze się te drzewa, które czynią następny pożar ciężkim — drobne, przygłuszone pnie i ciągłość paliwa — nie zręb zupełny w przebraniu odtwarzania. Po pierwszych wejściach sam ogień robi więcej konserwacji, jeśli menedżerowie go nadal używają. Jedno wypalenie, którego nigdy się nie powtarza, wraca paliwa.',
    ],
    where: [
      'Nazwana praktyka to federalny i międzyagencyjny ogień przepisany USA według PMS 484, używany przez Służbę Leśną i biura Interior na lasach narodowych, pastwiskach i ostojach. Zdjęcie karty to przepisane wypalenie Służby Leśnej w Bitterroot National Forest — pracujący ogień, nie plakat dzikiego pożaru. Odtwarzanie suchych mieszanych iglastych na inland West to typ lasu, którym zajmuje się GTR-292. Praktycy rdzenni tych samych krajobrazów używali ognia jako opieki nad ziemią dużo dłużej niż przewodnik z 2022 r.; encyklopedia nie udaje, że PMS 484 wynalazł ogień.',
      'Podobne planowe wypalanie jest używane w częściach Australii i w niektórych europejskich wrzosowiskach i sosnach. Te programy mają własne ustawy i reguły pogody. Ta strona nie wymyśla globalnej sumy hektarów. Idzie za amerykańskim przewodnikiem międzyagencyjnym i raportem technicznym o suchych mieszanych iglastych, na których stoi półka.',
    ],
    limits: [
      'Ogień przepisany nie zatrzymuje każdego megapożaru w fali upałów. Gdy paliwo, susza i wiatr się złożą, nawet traktowany drzewostan może spłonąć. Źle zaplanowane wypalenia uciekają. Dym to realny koszt zdrowia publicznego. Wypalenie robione, by „stworzyć projekt węglowy” albo otworzyć drogę pod sprzedaż drewna, nie jest celem PMS 484.',
      'To nie licencja klimatyczna na wyrąb. Branie dużych, odpornych na ogień drzew i nazywanie szlaku zrywkowego „redukcją paliwa” to inna działalność niż trzebież plus ogień przepisany, jak opisuje GTR-292. Traktujcie ogień przepisany jako konserwację krajobrazu według pisemnej recepty — PMS 484 z maja 2022, Służba Leśna i Interior — nie jako powód wyciąć stary drzewostan i nie jako gwarancję przeciw następnemu skrajnemu sezonowi.',
    ],
  },
  'shade-agroforestry': {
    title: 'Kawa i kakao w cieniu',
    hook: 'Kawa i kakao na pełnym słońcu zastępują okap lasu i tną siedlisko ptaków. Systemy cienia Smithsonian Bird Friendly trzymają roboczy piętro drzew nad uprawą — to nie druga karta agroleśnictwa w ogóle.',
    imageAlt: 'Krzewy kawy rosnące pod wysokim okapem drzew cienia na tradycyjnej plantacji',
    what: [
      'Kawa i kakao w cieniu to uprawy pod okapem drzew, nie na otwartej plantacji pełnego słońca. Bloki pełnego słońca zastępują strukturę lasu, tną siedlisko ptaków wędrownych i osiadłych i często potrzebują więcej nawozu i nawadniania. Tradycyjne i certyfikowane systemy cienia zostawiają kawę albo kakao jako uprawę pieniężną i drzewa jako dach. Ta strona jest o tej praktyce „okap nad towarem”. To nie szersza rodzina FAO upraw alejkowych, silwopastorażu i ogrodów przydomowych — to karta Agroleśnictwo na tej półce.',
      'Certyfikacja Bird Friendly Smithsonian Migratory Bird Center to nazwany standard naukowy, za którym idzie ta encyklopedia. Certyfikowane farmy są ekologiczne i bez wylesiania. 25-letni opis programu prowadzi badania do farm cienia w Meksyku i Gwatemali: farmy, które trzymają gęsty, różnorodny okap nad kawą, mogą trzymać siedlisko ptaków bliżej lasu niż plantacja słońca. PDF norm Bird Friendly ustawia mierzalne reguły cienia i różnorodności drzew używane w audytach. Tradycyjna farma cienia bez certyfikatu wciąż może być tą klasą rolnictwa; strony Smithsonian to sourced wzorzec, nie twierdzenie, że każda działka cienia jest audytowana.',
    ],
    how: [
      'Kawa albo kakao stoi w podszycie. Drzewa cienia — najlepiej mieszanka, a według reguł Bird Friendly w większości rodzime — tworzą okap powyżej. Artykuł Smithsonian na 25-lecie podaje progi ścieżki agroleśnej w certyfikacji: średnio 40 procent cienia nad kawą i 30 procent nad kakao, dziesięć gatunków drzew na hektar i większość drzew rodzimych. Osobna ścieżka ochrony lasu odkłada część farmy jako las; to inna droga zgodności, nie inna uprawa. Reguły ekologiczne nie dają insektycydom opróżnić owadów, które jedzą ptaki.',
      'Farma i tak musi zbierać wiśnie albo strąki, przycinać i sprzedawać. Cień nie zdejmuje potrzeby pracy ani kupca. Certyfikacja to audyt wobec PDF norm, nie kolor satelity. Jeśli okap scieńczono do jednego sadzonego gatunku grevillei, a farmę wciąż nazywają „cieniem”, wynik dla ptaków nie jest systemem badań Meksyku i Gwatemali. Ta encyklopedia nie wymyśla kary plonu ani premii; opisuje strukturę, którą mierzy program Smithsonian.',
    ],
    where: [
      'Badania, które uruchomiły Bird Friendly, zrobiono na kawie cieniowanej w Meksyku i Gwatemali. Zdjęcie na tej karcie to tradycyjny okap kawy cieniowanej w Gwatemali — ta sama klasa farmy, nie nazwane certyfikowane posiadłość. Program później dodał kakao i teraz certyfikuje farmy w Ameryce Łacińskiej i innych regionach kawy i kakao według tego samego pomysłu siedliska ptaków. Strona Smithsonian na 25-lecie to sourced historia; ten artykuł nie wymyśla listy krajów ani liczby farm poza tym opisem.',
      'Niecertyfikowane tradycyjne systemy cienia zostają zwykłym rolnictwem w częściach Ameryki Łacińskiej i Afryki Zachodniej. Są tematem tej karty, gdy trzymają prawdziwy okap nad kawą albo kakao. Nie są dowodem, że plantacja słońca z kilkoma ozdobnymi drzewami przy drodze to „agroleśnictwo”, i nie są amazońską chakrą ani aleją Środkowego Zachodu — te należą do strony Agroleśnictwo.',
    ],
    limits: [
      'Cień sam z siebie nie zatrzymuje wylesiania, jeśli ceny pchają nową karczowiznę na krawędzi lasu. Certyfikacja jest tak uczciwa, jak audyt. Pieczęć Bird Friendly to standard farmy, nie krajowy plan użytkowania ziemi. Intensyfikacja na pełnym słońcu istnieje, bo może podnieść krótki plon na danym hektarze; ta strona nie wymyśla wielkości tej luki.',
      'To nie druga karta agroleśnictwa. Trzy typy systemów FAO — drzewa z uprawami, drzewa ze zwierzętami, drzewa z jednymi i drugimi — to szersza rodzina. Kawa i kakao w cieniu to jedna praktyka towaru pod okapem z normami Smithsonian. Nie łączcie dwóch slugów. Traktujcie kawę i kakao w cieniu jako roboczy okap nad uprawą napoju, badaną przez 25 lat w Meksyku i Gwatemali — nie jako ogólny offset sadzenia drzew i nie jako każdy system agroleśny na Ziemi.',
    ],
  },
  agroforestry: {
    title: 'Agroleśnictwo',
    hook: 'Wycinanie drzew z upraw i pastwisk zostawia glebę, cień i paszę cieńszymi. FAO traktuje agroleśnictwo jako drzewa świadomie łączone z uprawami i zwierzętami — szerszą rodzinę niż kawa cieniowana.',
    imageAlt:
      'Widok z lotu ptaka: uprawy alejkowe i rzędy młodych drzew na farmie Savanna Institute nad rzeką Wisconsin',
    what: [
      'Agroleśnictwo to zbiorcza nazwa systemów użytkowania ziemi, w których wieloletnie drzewiaste — drzewa, krzewy, palmy, bambusy — są świadomie uprawiane z uprawami rolnymi i/albo zwierzętami, w przestrzeni albo w czasie, tak że części na siebie działają. Przegląd FAO to definicja tej strony. Wycinanie drzew z upraw i pastwisk zostawia glebę, cień i paszę cieńszymi. Gospodarstwa wtedy mocniej opierają się na nawozie, nawadnianiu i paszy z zewnątrz. Wracanie drzew do gospodarstwa to praktyka; to nie offset leśny i nie hasło szkółki.',
      'FAO nazywa trzy główne typy. Systemy agrisilwikulturowe łączą drzewa i uprawy — uprawy alejkowe, ogrody przydomowe. Systemy silwopastoralne łączą drzewa i wypas, także na pastwiskach. Systemy agrosilwopastoralne łączą drzewa, zwierzęta i uprawy. Te trzy typy to mapa tej karty. Kawa i kakao w cieniu siedzą w rodzinie agrisilwikulturowej jako towar pod okapem, ale mają własną stronę encyklopedii — normy Smithsonian Bird Friendly, badania Meksyku i Gwatemali. Ta karta to szersza rodzina FAO, w tym systemy, w których nie ma kawy.',
    ],
    how: [
      'Projekt jest lokalny. Gatunki, rozstaw i kolejność muszą pasować do klimatu, gospodarstwa i rynku. Uprawa alejkowa stawia rzędy drzew między pasami uprawy jednorocznej. Ogród przydomowy układa owoce, drewno i warzywa na małej działce. Silwopastoraż trzyma trawę i żer pod piętrem drzew, żeby zwierzęta miały cień, a drzewa drugi produkt. FAQ FAO i moduł agroleśnictwa w skrzynce SFM traktują te układy jako zwykłą praktykę wiejską, która wciąż potrzebuje interdyscyplinarnej rady: złe drzewo na polu to konkurencja, nie usługa.',
      'Prawo i czas są częścią metody. Drzewa, które ktoś inny spasie albo zetnie, nikt nie będzie pielęgnował. Rząd sadzonek, którego nigdy się nie przycina i nie chroni, to nie system. FAO podkreśla, że agroleśnictwo trzeba kroić pod rolnika i miejsce. Ta encyklopedia nie wymyśla globalnego plonu ani współczynnika węgla. Opisuje trzy typy systemów i nazwany przykład poniżej.',
    ],
    where: [
      'FAO mówi, że agroleśnictwo jest istotną cechą rolnictwa we wszystkich regionach, częstsze w Azji Południowo-Wschodniej, Ameryce Środkowej i Południowej, i szacuje, że około 78 procent globalnej powierzchni pod agroleśnictwem jest w tropikach, a około 22 procent w strefie umiarkowanej. To liczby przeglądu FAO, nie spis Fix Planet. Umiarkowana uprawa alejkowa — farma nad rzeką Wisconsin na zdjęciu karty jest tą klasą działki — to ta sama rodzina w innym klimacie.',
      'Nazwany tradycyjny system w własnym artykule FAO to amazońska chakra prowincji Napo w Ekwadorze: wielopiętrowy system agroleśny prowadzony przez wspólnoty rdzenne, uznany w pracy FAO nad GIAHS. Używajcie tego artykułu FAO, nie martwej ścieżki GIAHS strony trzeciej. Chakra to nie posiadłość kawy cieniowanej i nie wiatrochron Wielkich Równin. To drzewa, uprawy i zarządzanie wspólnotowe w amazońskim Ekwadorze — jeden udokumentowany przypadek szerszej rodziny.',
    ],
    limits: [
      'Rząd sadzonek to nie offset leśny. Agroleśnictwo nie odtwarza lasu pierwotnego i nie zatrzymuje frontu, jeśli następny hektar wciąż jest tańszy do wycięcia niż do pielęgnacji. Drzewa konkurują z uprawami o światło i wodę, gdy projekt jest zły. Zwierzęta bez pasterza zjedzą przyszły okap.',
      'Nie łączcie tej karty z kawą i kakao w cieniu. Te systemy to jedna praktyka agrisilwikulturowa ze standardem ptasim Smithsonian; ta karta to trzy typy FAO plus chakra Napo. Nie wklejajcie tu liczb leśnictwa wspólnotowego Meksyku albo Tanzanii. Traktujcie agroleśnictwo jako drzewa z gospodarstwami — aleja, pastwisko, ogród, chakra — nie jako drugą stronę Bird Friendly i nie jako inwentaryzację lasu sadzonego.',
    ],
  },
  windbreaks: {
    title: 'Wiatrochrony / pasy wiatrochronne',
    hook: 'Otwarte pola biorą cały wiatr: gleba wywiewa, śnieg zawiewa, zwierzęta spalają paszę. Krajowe Centrum Agroleśnictwa USDA traktuje wiatrochrony jako zaprojektowane nasadzenia liniowe — infrastrukturę rolną, nie plantację węglową.',
    imageAlt: 'Dwa młode rzędy drzew na palikach tworzące wiatrochron na zielonym polu w Illinois',
    what: [
      'Wiatrochrony — zwane też shelterbelts — to liniowe nasadzenia drzew i krzewów ułożone, by spowolnić wiatr i robić pokrewne prace rolne: ochrona pola, schronienie dla zwierząt, żywe płoty śnieżne, osłona zagrody. Strona wiatrochronów Krajowego Centrum Agroleśnictwa USDA to definicja tej encyklopedii. Otwarte pola i podwórza biorą cały wiatr. Gleba wywiewa, śnieg zawiewa na drogi, zwierzęta w zimnie spalają więcej paszy. Zaprojektowany pas drzew to zwykła odpowiedź Środkowego Zachodu i Wielkich Równin.',
      'NAC mówi wprost, że wiatrochrony nie są jednego rozmiaru. Położenie, orientacja względem wiatru, wysokość, szerokość, zagęszczenie i gatunki decydują, co pas robi. Jedne mają głównie ciąć prędkość wiatru nad uprawą. Inne trzymać śnieg na polu, zdejmować go z drogi, dawać cień zwierzętom albo chować zagrodę. Agroforestry Notes 25 i 36 to notatki techniczne Centrum o tych wyborach projektu. To infrastruktura rolna. To nie inwentaryzacja plantacji i nie okap kawy cieniowanej.',
    ],
    how: [
      'Wysokość ustawia strefę chronioną: ciche powietrze po stronie zawietrznej skaluje się z tym, jak wysokie są drzewa. Zagęszczenie — jak porowaty jest pas — ustawia, czy wiatr spada ostro i potem wraca, czy jest łagodzony na dłuższym odcinku. Luki stają się strumieniami; brakujące drzewo to dziura, która może wywiać glebę. Orientacja zwykle w poprzek panującego szkodliwego wiatru. Notatki 25 i 36 przechodzą te związki i pasy wielorzędowe kontra jednorzędowe, w tym dlaczego młody trójrzędowy pas — zdjęcie z Illinois na tej karcie — to inne narzędzie niż dojrzały wielopiętrowy pas.',
      'Założenie to sadzenie, odchwaszczanie i wymiana martwych drzew, aż pas się zamknie. Renowacja to późniejsza robota: stare pasy Równin mają luki, samosiew i utracone zagęszczenie. NAC i partnerzy pracują nad inwentaryzacją, zakładaniem i renowacją, w tym mapowaniem wiatrochronów Wielkich Równin. Specjalistyczne krzewy można dodać na drugi produkt, jeśli zbiór nie psuje funkcji wiatrowej. Pas, którego nigdy się nie dosadza po zamieraniu, to rząd snagów, nie wiatrochron.',
    ],
    where: [
      'Nazwana praktyka to amerykańskie wiatrochrony rolne, jak opisuje je USDA NAC: pasy polne, dla zwierząt, żywe płoty śnieżne i pasy zagrody, z długą historią Wielkich Równin i Środkowego Zachodu. Zdjęcie karty to młody trójrzędowy pas na polu w Illinois — ta klasa nasadzenia, nie nazwany projekt USDA. NAC notuje, że producenci używają wiatrochronów głównie dla gleby, zwierząt, wiatru i śniegu, a satysfakcja w syntetyzowanych badaniach była wysoka. Ta strona nie wymyśla krajowego kilometrażu.',
      'Liniowe pasy wiatrochronne istnieją też w innych wietrznych regionach rolniczych. Ta encyklopedia nie kopiuje tych programów na notatki USDA. Linki weryfikacji to strona wiatrochronów NAC oraz Notes 25 i 36. Jeśli kolejny pakiet nazwie system innego kraju z żywym źródłem, można go dodać; do tego czasu sourced praktyka to projekt NAC USA.',
    ],
    limits: [
      'Wiatrochrony zawodzą, jeśli ich się nie utrzymuje. Luki, zaniedbane rzędy i pas sadzony równolegle do szkodliwego wiatru nie chronią pola. To nie plantacja węglowa: cienka linia drzew nie zastępuje inwentaryzacji lasu ani offsetu klimatycznego. Nie zatrzymują suszy. Nie zastępują roboty bufora nadrzecznego — zacienić ciek; to inna karta.',
      'Wiatrochron to nie agroleśnictwo w sensie trzech typów FAO, poza jednym liniowym narzędziem silwoornym albo zagrodowym, i nie kawa cieniowana. Traktujcie go jako zaprojektowaną infrastrukturę rolną — wysokość, zagęszczenie, orientacja, Notes 25 i 36 — nie jako odtwarzanie zadrzewienia i nie jako miejsce wymyślić procent plonu, którego ta strona z tych notatek nie ma.',
    ],
  },
  'reduced-impact-logging': {
    title: 'Pozyskanie o zmniejszonym wpływie',
    hook: 'Zwykły zbiór tropikalny często niszczy pozostały drzewostan nieplanowanymi szlakami zrywkowymi i drzewami zawieszonymi. Pozyskanie o zmniejszonym wpływie to planowany wyrąb i zrywka — nie zakaz wycinki i nie to samo, co zostawienie starego lasu nietkniętego.',
    imageAlt: 'Żółta ładowarka niesie kłodę w obozie pozyskania w dystrykcie Tawau, Sabah, las w tle',
    what: [
      'Pozyskanie o zmniejszonym wpływie (RIL) to wyrąb zaplanowany i wykonany tak, by szkody w pozostałym lesie były mniejsze: zmapować drzewa towarowe, rozłożyć drogi i szlaki zrywkowe, ścinać w wybranym kierunku i trzymać maszyny na planowanych szlakach. Artykuł Dennisa Dykstry dla FAO o pojęciach i kwestiach traktuje RIL jako zastosowanie znanej inżynierii pozyskania — inwentaryzacja, nadzór, kierunkowy wyrąb, cięcie lian tam, gdzie korony są związane — przeniesione do lasów tropikalnych, gdzie na hektarze stoi tylko kilka drzew handlowych. Zwykły zbiór tropikalny często oznacza źle zaplanowane szlaki, drzewa zawieszone w lianach i uszkodzenie następnego plonu. Pozostały drzewostan i gleba płacą pierwsze.',
      'Artykuł W. B. J. Jonkersa dla FAO prowadzi pierwszy prawdziwy system RIL dla tropikalnego lasu deszczowego do końca lat 70. na Sarawaku, potem do późniejszej pracy w Surinamie, Gujanie i Kamerunie. Pinard i inni użyli nazwy „reduced-impact logging” w 1995 r.; Dykstra notuje, że termin się przyjął, bo był bardziej akceptowalny niż starsze sformułowanie FAO. RIL samo z siebie nie jest zrównoważoną gospodarką leśną i nie jest tytułem wspólnotowym. To metoda pozyskania. Zdjęcie obozu na tej karcie to składnica w Sabah — sceneria przemysłowa, nie nazwana powierzchnia próbna RIL.',
    ],
    how: [
      'Lista Dykstry to zwykła sekwencja. Inwentaryzacja i mapowanie drzew towarowych przed wyrębem. Planowanie dróg, szlaków i składnic, by dojść do tych drzew i chronić cieki. Cięcie lian wokół drzew, które inaczej pociągnęłyby sąsiadów. Kierunkowy wyrąb i staranne przerzynanie. Maszyny zostają na oznaczonych szlakach; kłody wciąga się wyciągarką, a nie poluje skidderem po drzewostanie. Ocena po wyrębie mówi brygadzie, co uszkodzili. Prawie wszystko to jest zwykłe w umiarkowanym lesie przemysłowym; tropikalne dodatki to mapowanie rozproszonych drzew towarowych i cięcie lian.',
      'Jonkers pokazuje, dlaczego te same idee na ziemi wyglądają inaczej. Metoda Sarawaku z końca lat 70. używała map terenu i drzew, wyrębu w jodełkę ku wcześniej otwartym szlakom głównym i tych samych maszyn co zwykły wyrąb — koszt metra sześciennego spadł, a drzew zniszczonych było prawie o połowę mniej, choć redukcja szkód nie była pierwotnym zadaniem. Gujana i Kamerun dostosowały rozstaw szlaków, cięcie lian i cele wyrębu do uboższych drzewostanów, skupionych gatunków i, w Kamerunie, ludzi mieszkających w lesie. Metoda to planowanie i nadzór, nie nowa piła.',
    ],
    where: [
      'Nazwane przypadki FAO to Sarawak (pierwszy pełny system, koniec lat 70.), potem Surinam, Gujana (w tym praca Tropenbos koło Mabura Hill) i Kamerun (Tropenbos na południowym zachodzie). Inne badania lat 90., które wymienia Jonkers — Indonezja, Sabah, Brazylia — siedzą w tej samej fali badawczej. Artykuł Dykstry to część pojęciowa: kodeksy praktyki, szkolenie i dlaczego operacje tropikalne naruszają więcej gruntu na metr sześcienny niż zręb Północno-Zachodniego Pacyfiku setek metrów sześciennych na hektar.',
      'Badania w tych artykułach znajdowały mniejsze szkody i w kilku próbach koszty nie wyższe albo niższe niż zwykły wyrąb, bo mniej drewna marnowano i zrywka była krótsza. Jonkers i Dykstra mówią też wprost, że wiele firm praktyki nadal nie zmienia. Ta strona nie wymyśla globalnego udziału zbioru tropikalnego, który jest RIL. Sourced fakt: metoda istnieje, testowano ją w tych krajach i nie przyjmuje się jej automatycznie.',
    ],
    limits: [
      'RIL to nie zakaz wycinki i nie to samo, co zostawienie starego lasu nietkniętego. Planowany wyrąb i tak zabiera drzewa, otwiera okap i buduje drogi, które mogą zaprosić osadnictwo — Dykstra notuje dodatkowe kilometry tropikalnej drogi na metr sześcienny. Jeśli inwentaryzacja jest fikcją albo skidder schodzi ze szlaku, etykieta to farba.',
      'Szkolenie i codzienny nadzór to ograniczenie, które nazywają oba artykuły. Bez sprawnych pilarzy i nadzorcy na ziemi RIL to PDF. Nie tworzy inwentaryzacji lasu sadzonego, grupy użytkowników wspólnotowych ani farmy kawy przyjaznej ptakom. Traktujcie to jako planowane pozyskanie tropikalne — przypadki Jonkersa na Sarawaku, w Gujanie i Kamerunie; pojęcia Dykstry — nie jako świadectwo, że koncesja jest dziczą.',
    ],
  },
  'riparian-forest-restoration': {
    title: 'Odtwarzanie lasów nadrzecznych',
    hook: 'Gdy drzewa nad ciekiem są wycinane, brzegi erodują, składniki spływają, letnia woda się grzeje. Climate Hubs USDA i podręcznik Służby Leśnej o odtwarzaniu nadrzecznym traktują naprawę jako pokrywę na brzegu — lokalną pracę przy cieku, nie hasło zlewni.',
    imageAlt: 'Widok z lotu ptaka: zadrzewiony bufor nadrzeczny wzdłuż wijącego się cieku wśród pól w hrabstwie Story, Iowa',
    what: [
      'Odtwarzanie lasu nadrzecznego to praca wracania pokrywy drzewiastej i innej roślinnej na ziemię przy cieku, rzece albo mokrym rowie, żeby brzeg trzymał, woda była w cieniu, a koryto miało korzenie i drewno. Climate Hubs USDA opisują lasy w strefach nadrzecznych jako zmniejszające erozję, buforujące wezbrania, łagodzące temperaturę, tnące parowanie i dające korytarze. Gdy te drzewa wycina się pod pola albo działki, brzegi erodują, składniki spływają, letnia woda się grzeje. Ryby i koryto tracą cień i korzenie, które trzymały krawędź.',
      'Sąsiednia strona Hubs o utrzymaniu albo odtworzeniu stref nadrzecznych oraz podręcznik Służby Leśnej USDA o odtwarzaniu nadrzecznym (niskorozdzielczy PDF cytowany tutaj) to podręczniki praktyki tej encyklopedii. Cel to cień, rumosz drzewny i gleba na korzeniach — mieszane nasadzenia, bufory bez wyrębu albo z ograniczonym wyrębem i umocnienie brzegu tam, gdzie podnóże już się sypie. To nie inwentaryzacja lasu sadzonego, nie wiatrochron przez suche pole i nie leśnictwo wspólnotowe Nepalu. To pas lasu wzdłuż wody.',
    ],
    how: [
      'Taktyki Climate Hubs są konkretne. Odtworzyć mieszankę gatunków drzew i roślin, by zwiększyć cień, dać drewno korytu, ustabilizować glebę i znów połączyć siedliska. Zalesić grunt nadrzeczny obok rolnictwa albo zabudowy, by ciąć erozję i ładunek składników. Tworzyć bufory z ograniczonym wyrębem albo bez, dopasowane do rzeźby i hydrologii, nie tylko do jednej reklamowanej szerokości. Trzymać okap i pokrywę gruntu, by deszcz nie bił w gołą glebę. Gdzie brzegi już się sypią — kotwić tkaniną, drutem albo materiałami naturalnymi. Gdzie są tamy albo zastawki — zarządzać wodą tak, by gleba nadrzeczna nie zostawała sucha w złym momencie.',
      'Podręcznik Służby Leśnej prowadzi przez ocenę stanowiska, gatunki, sadzenie i różnicę między żywym buforem a zrzutem kamienia. Posadzenie jednego rzędu jednego gatunku na surowym brzegu to nie podręcznik. Bydło stojące w korycie przekreśli sezon pracy. Bufor musi być dość szeroki dla rzeźby; dekoracyjna linia drzew na wyprostowanym rowie to nie odtworzony las nadrzeczny.',
    ],
    where: [
      'Nazwane wskazówki są federalne amerykańskie: podejścia adaptacyjne Climate Hubs dla zalesionych zlewni oraz podręcznik Służby Leśnej o odtwarzaniu nadrzecznym. Zdjęcie karty to zadrzewiony bufor na Bear Creek w hrabstwie Story, Iowa — kraj farm z pasem drzew przy cieku, zwykły obraz Środkowego Zachodu tej praktyki. Podobne bufory są używane na ciekach rolniczych w innych krajach umiarkowanych; ta strona nie wymyśla ich długości ani globalnego kilometrażu.',
      'Projekty idą w lasach publicznych, na kontraktach ochrony rolnej i na ciekach miejskich. Już działają. To nie pilotaż czekający na nowy wynalazek. Źródła powyżej to linki weryfikacji; nie twierdzą, że każdy ciek USA ma bufor.',
    ],
    limits: [
      'Posadzony pas nie odtwarza całej zlewni, jeśli górne tereny zostają gołe. Składniki i osad i tak przychodzą z pola. Bufor to nie oczyszczalnia i nie wał. Przy dużej powodzi koryto się przesunie. W suchym roku nasadzenia padną, jeśli gatunek był zły dla poziomu wody.',
      'To lokalna praca przy cieku. To nie licencja klimatyczna ignorować resztę zlewni i nie agroleśnictwo ani kawa cieniowana dlatego, że posadzono kilka wierzb. Traktujcie odtwarzanie nadrzeczne jako pokrywę na brzegu — taktyki Hubs plus podręcznik Służby Leśnej — nie jako statystykę powierzchni lasu i nie jako zamianę za trzymanie bydła i pługa z dala od wody.',
    ],
  },
  'community-forestry': {
    title: 'Leśnictwo wspólnotowe',
    hook: 'Gdy prawa użytkowania siedzą tylko w dalekim urzędzie, okoliczne gospodarstwa nie mają powodu strzec lasu, którego nie mogą legalnie używać. Ustawa leśna Nepalu z 1993 r. i system CFUG to sourced model tej karty — nie kopia Meksyku albo Tanzanii.',
    imageAlt: 'Wysokie sosny i drzewa liściaste na trawiastym stoku lasu wspólnotowego Badikhel, Lalitpur, Nepal',
    what: [
      'Leśnictwo wspólnotowe to zarządzanie lasem, w którym lokalni ludzie mają uznane prawa użytkować i dbać o określony las według reguł, które pomagają ustalać, zamiast by państwo było jedynym legalnym gospodarzem. Starsza notatka FAO o leśnictwie wspólnotowym traktuje to przesunięcie praw i obowiązków jako rdzeń pomysłu. Gdy prawa użytkowania siedzą tylko w dalekim urzędzie, okoliczne gospodarstwa nie mają powodu strzec lasu, którego nie mogą legalnie używać. Dalej idzie nielegalny wyrąb i słaba opieka. Tytuł grupy użytkowników to odwrotny układ: ludzie przy drzewach mogą brać to, na co pozwalają reguły, i mają chronić resztę.',
      'Ta karta to system Nepalu, nie kolaż innych krajów. Forest Act, 2049 (1993) — tekst FAOLEX cytowany tutaj — to ustawa, która dała grupom użytkowników lasów wspólnotowych prawną drogę do zarządzania lasem państwowym przekazanym jako las wspólnotowy. FAO i Federacja Użytkowników Lasów Wspólnotowych Nepalu (FECOFUN) w nocie z 28 lipca 2025 r. opisują obecną skalę: ponad 23 000 CFUG zarządzających około 2,4 miliona hektarów, obejmujących około 16 milionów ludzi. To liczby FAO/FECOFUN. Ta strona nie dodaje ejidos Meksyku ani lasów wioskowych Tanzanii, jakby to było to samo prawo.',
    ],
    how: [
      'CFUG to lokalne zgromadzenie z konstytucją, planem operacyjnym i granicą. Grupa decyduje, kto może brać opał, drewno i paszę, co idzie do funduszu grupy i jak chodzą patrole. Ustawa z 1993 r. to haczyk prawny, który czyni ten plan czymś więcej niż zwyczajem wioski. Okręgowi leśnicy zostają w obrazie; przekazanie to proces ustawowy, nie hasło. FECOFUN to federacja użytkowników, która targuje się z państwem i z programami FAO o szkolenie, przedsiębiorstwa i projekty odporności klimatycznej.',
      'Metoda zawodzi, gdy grupę przejmą, gdy kobiety i użytkownicy rdzenni zostają poza komitetem albo gdy rynek drewna ogołaca drzewostan szybciej, niż zakładał plan operacyjny. Tekst spotkania FAO i FECOFUN z 2025 r. podkreśla przedsiębiorstwa, przywództwo kobiet i przejrzyste dane — bo tytuł na papierze nie jest automatyczną ochroną. Zdjęcie to las wspólnotowy Badikhel w Lalitpur: nazwany nepalski las wspólnotowy, nie ogólne „wioskowe zadrzewienie”.',
    ],
    where: [
      'Nepal to sourced geografia. Ustawa z 1993 r. działa tam. Liczby FAO/FECOFUN z 2025 r. — ponad 23 000 grup, około 2,4 miliona hektarów, około 16 milionów ludzi — to liczby leśnictwa wspólnotowego Nepalu. Środkowe wzgórza to klasyczny krajobraz; programy Churia i wschodnie wspomniane w tej nocie FAO to późniejsze warstwy, nie drugi kraj.',
      'Inne państwa prowadzą schematy lasów wspólnotowych albo wioskowych według innych ustaw. Ta encyklopedia nie klei ich statystyk na ustawę Nepalu. Jeśli późniejszy pakiet doda inny kraj z żywym tekstem prawnym i żywą liczbą urzędową, może mieć własny akapit. Do tego czasu nie traktujcie tej karty jako Meksyku albo Tanzanii.',
    ],
    limits: [
      'Tytuł grupy użytkowników nie jest automatyczną ochroną. Grupy mogą przerąbać, wykluczyć kobiety albo stać się drwalnią lokalnej elity. Rynki, które płacą za czyste pnie, naciskają na plan operacyjny. Państwo wciąż może odebrać albo wstrzymać przekazanie. Nota FAO z 2025 r. to historia partnerstwa, nie spis stanu każdego hektara.',
      'Nie kopiujcie tu liczb leśnictwa wspólnotowego innych krajów. Nie łączcie tej karty ze zrównoważonymi plantacjami, ANR w Nigrze ani kawą cieniowaną. Traktujcie leśnictwo wspólnotowe tutaj jako ustawę Nepalu z 1993 r. i skalę FAO/FECOFUN z 2025 r. — ponad 23 000 CFUG, około 2,4 miliona hektarów, około 16 milionów ludzi — i jako metodę zarządzania, która wciąż potrzebuje rozliczalnych grup.',
    ],
  },
};
